dist: trusty
sudo: required

language: node_js
node_js:
  - "stable"
addons:
  sonarcloud:
    organization: "PallaviKsai"
    token:
      secure: "4dff8f6b8c25b095d33e0906f68118fa17de71f5"
  sauce_connect:
    username: "PallaviKsai18"
    access_key: "148bb4e2-6a5c-40dc-8955-a9f90f371198"
    
script:
  - sonar-scanner
